import { Router } from 'express';
import { requireAuth, allowRoles } from '../../middlewares/auth.middleware.js';
import { validate } from '../../middlewares/validate.middleware.js';
import { createCourseSchema, updateCourseSchema, courseIdSchema, createModuleSchema, updateModuleSchema, moduleIdSchema, createLessonSchema, updateLessonSchema, lessonIdSchema } from '../../validators/course.validator.js';
import { createRecordedCourse, listManagedCourses, getManagedCourse, updateRecordedCourse, submitCourseForReview, createModule, updateModule, deleteModule, createLesson, updateLesson, deleteLesson } from '../../controllers/course.controller.js';
const router = Router();
router.use(requireAuth, allowRoles('instructor'));
router.get('/courses', listManagedCourses);
router.post('/courses', validate(createCourseSchema), createRecordedCourse);
router.get('/courses/:id', validate(courseIdSchema), getManagedCourse);
router.patch('/courses/:id', validate(updateCourseSchema), updateRecordedCourse);
router.post('/courses/:id/submit-review', validate(courseIdSchema), submitCourseForReview);
router.post('/courses/:courseId/modules', validate(createModuleSchema), createModule);
router.patch('/modules/:moduleId', validate(updateModuleSchema), updateModule);
router.delete('/modules/:moduleId', validate(moduleIdSchema), deleteModule);
router.post('/modules/:moduleId/lessons', validate(createLessonSchema), createLesson);
router.patch('/lessons/:lessonId', validate(updateLessonSchema), updateLesson);
router.delete('/lessons/:lessonId', validate(lessonIdSchema), deleteLesson);
export default router;
